-- Wire spots.image_url → public Storage URLs. GENERATED by build-image-urls.mjs.
-- Run in the Supabase SQL editor after uploading the images to the `spots` bucket.
begin;
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/nashville/john-seigenthaler-pedestrian-bridge.webp' where id = 'john-seigenthaler-pedestrian-bridge';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/nashville/capitol-boulevard.webp' where id = 'capitol-boulevard';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/nashville/deaderick-street.webp' where id = 'deaderick-street';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/nashville/woodland-street-bridge.webp' where id = 'woodland-street-bridge';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/nashville/fort-nashborough.webp' where id = 'fort-nashborough';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/nashville/symphony-place.webp' where id = 'symphony-place';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/nashville/whatliftsyou.webp' where id = 'whatliftsyou';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/nashville/mixtape-memories-mural-wedgewood-houston.webp' where id = 'mixtape-memories-mural-wedgewood-houston';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/nashville/printers-alley.webp' where id = 'printers-alley';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/nashville/arcade-street.webp' where id = 'arcade-street';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/nashville/parthenon.webp' where id = 'parthenon';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/nashville/belmont-mansion.webp' where id = 'belmont-mansion';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/nashville/capitol-hill.webp' where id = 'capitol-hill';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/atlanta/fairlie-poplar-historic-district.webp' where id = 'fairlie-poplar-historic-district';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/atlanta/atl-nighthawks-at-the-diner.webp' where id = 'atl-nighthawks-at-the-diner';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/atlanta/look-at-them-look-at-us.webp' where id = 'look-at-them-look-at-us';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/atlanta/state-farm-arena.webp' where id = 'state-farm-arena';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/atlanta/underground-atlanta.webp' where id = 'underground-atlanta';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/atlanta/podium-plaza.webp' where id = 'podium-plaza';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/atlanta/olympic-rings.webp' where id = 'olympic-rings';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/atlanta/atlanta-botanical-garden.webp' where id = 'atlanta-botanical-garden';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/atlanta/woodruff-park.webp' where id = 'woodruff-park';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/atlanta/liberty-plaza.webp' where id = 'liberty-plaza';
update public.spots set image_url = 'https://yqulquuzhkiwbucpqdcm.supabase.co/storage/v1/object/public/spots/atlanta/georgia-aquarium.webp' where id = 'georgia-aquarium';
commit;
