// ---------------------------------------------------------------------------
// Vantage content pipeline — build the Postgres seed (Serve stage).
//
// Reads the committed content/<city>.json files and emits a single seed.sql
// (upserts into public.cities + public.spots) that you paste into the Supabase
// SQL editor AFTER schema.sql. Dollar-quoting ($vtg$…$vtg$) keeps the apostrophes
// and quotes in the copy safe — no escaping, no service-role key needed.
//
// Idempotent: re-running the seed updates rows in place and does NOT touch
// image_url (populated later by the Image slice), so it's safe to re-seed.
//
// Run:  npm run seed
// ---------------------------------------------------------------------------

import { readFileSync, writeFileSync, existsSync } from "fs";

// Which content files make up each city (hand-authored core + drafted expansion).
const CITIES = {
  nashville: { name: "Nashville", region: "TN", lat: 36.1627, lon: -86.7816, files: ["nashville.json"] },
  atlanta:   { name: "Atlanta", region: "GA", lat: 33.7490, lon: -84.3880, files: ["atlanta-core.json", "atlanta.json"] },
};

const dq = (s) => (s == null ? "null" : `$vtg$${String(s)}$vtg$`);
const arr = (a) => (a && a.length ? `array[${a.map(dq).join(", ")}]::text[]` : `'{}'::text[]`);
const num = (n) => (n == null ? "null" : String(n));

const out = [
  "-- Vantage content seed — GENERATED by content-pipeline/build-seed.mjs.",
  "-- Run in Supabase → SQL Editor AFTER schema.sql. Idempotent (safe to re-run).",
  "begin;",
];

const seen = new Set();
for (const [key, city] of Object.entries(CITIES)) {
  out.push(`\n-- ${city.name} ------------------------------------------------------------`);
  out.push(
    `insert into public.cities (id, name, region, center_lat, center_lon, published) values ` +
    `(${dq(key)}, ${dq(city.name)}, ${dq(city.region)}, ${num(city.lat)}, ${num(city.lon)}, true)`,
    `  on conflict (id) do update set name=excluded.name, region=excluded.region, ` +
    `center_lat=excluded.center_lat, center_lon=excluded.center_lon, published=excluded.published;`
  );
  let count = 0;
  for (const file of city.files) {
    const path = new URL(`./content/${file}`, import.meta.url);
    if (!existsSync(path)) { console.warn(`  ! missing content/${file} — skipped`); continue; }
    for (const s of JSON.parse(readFileSync(path, "utf8"))) {
      if (seen.has(s.id)) console.warn(`  ! duplicate spot id "${s.id}" (${s.name}) — later one wins`);
      seen.add(s.id);
      const genres = s.genres?.length ? s.genres : (s.genre ? [s.genre] : []);
      out.push(
        `insert into public.spots (id, city_id, name, type, genres, window_type, reason, tagline, why, look, getting, image_url, lat, lon, published) values (`,
        `  ${dq(s.id)}, ${dq(key)}, ${dq(s.name)}, ${dq(s.type)}, ${arr(genres)}, ${dq(s.windowType)}, ${dq(s.reason)}, ${dq(s.tagline)}, ${dq(s.why)}, ${arr(s.look)}, ${dq(s.getting)}, null, ${num(s.lat)}, ${num(s.lon)}, true)`,
        // image_url intentionally omitted from the update set — the Image slice owns it.
        `  on conflict (id) do update set city_id=excluded.city_id, name=excluded.name, type=excluded.type, ` +
        `genres=excluded.genres, window_type=excluded.window_type, reason=excluded.reason, tagline=excluded.tagline, ` +
        `why=excluded.why, look=excluded.look, getting=excluded.getting, lat=excluded.lat, lon=excluded.lon, published=excluded.published;`
      );
      count++;
    }
  }
  console.log(`  ${city.name}: ${count} spots`);
}
out.push("\ncommit;");

const dest = new URL("../vantage/supabase/seed.sql", import.meta.url);
writeFileSync(dest, out.join("\n") + "\n");
console.log(`\nwrote vantage/supabase/seed.sql  (${seen.size} spots across ${Object.keys(CITIES).length} cities)`);
