// GENERATED from vantage/lib/cameras.catalog.json by content-pipeline/build-gear.mjs.
// DO NOT EDIT — edit the JSON and re-run `node build-gear.mjs`. Guarded by parity.test.ts.
export type CameraRow = { id: string; model: string; cropFactor: number; fixedLens?: { minFocal: number; maxFocal: number; maxAperture: number } };

export const CAMERAS: Record<string, CameraRow> = {
  "fuji-x100": { id: "fuji-x100", model: "X100", cropFactor: 1.5, fixedLens: { minFocal: 23, maxFocal: 23, maxAperture: 2 } },
  "fuji-x100s": { id: "fuji-x100s", model: "X100S", cropFactor: 1.5, fixedLens: { minFocal: 23, maxFocal: 23, maxAperture: 2 } },
  "fuji-x100t": { id: "fuji-x100t", model: "X100T", cropFactor: 1.5, fixedLens: { minFocal: 23, maxFocal: 23, maxAperture: 2 } },
  "fuji-x100f": { id: "fuji-x100f", model: "X100F", cropFactor: 1.5, fixedLens: { minFocal: 23, maxFocal: 23, maxAperture: 2 } },
  "fuji-x100v": { id: "fuji-x100v", model: "X100V", cropFactor: 1.5, fixedLens: { minFocal: 23, maxFocal: 23, maxAperture: 2 } },
  "fuji-x100vi": { id: "fuji-x100vi", model: "X100VI", cropFactor: 1.5, fixedLens: { minFocal: 23, maxFocal: 23, maxAperture: 2 } },
  "fuji-x70": { id: "fuji-x70", model: "X70", cropFactor: 1.5, fixedLens: { minFocal: 18.5, maxFocal: 18.5, maxAperture: 2.8 } },
  "fuji-xf10": { id: "fuji-xf10", model: "XF10", cropFactor: 1.5, fixedLens: { minFocal: 18.5, maxFocal: 18.5, maxAperture: 2.8 } },
  "fuji-xpro1": { id: "fuji-xpro1", model: "X-Pro1", cropFactor: 1.5 },
  "fuji-xpro2": { id: "fuji-xpro2", model: "X-Pro2", cropFactor: 1.5 },
  "fuji-xpro3": { id: "fuji-xpro3", model: "X-Pro3", cropFactor: 1.5 },
  "fuji-xe2": { id: "fuji-xe2", model: "X-E2", cropFactor: 1.5 },
  "fuji-xe3": { id: "fuji-xe3", model: "X-E3", cropFactor: 1.5 },
  "fuji-xe4": { id: "fuji-xe4", model: "X-E4", cropFactor: 1.5 },
  "fuji-xt1": { id: "fuji-xt1", model: "X-T1", cropFactor: 1.5 },
  "fuji-xt2": { id: "fuji-xt2", model: "X-T2", cropFactor: 1.5 },
  "fuji-xt3": { id: "fuji-xt3", model: "X-T3", cropFactor: 1.5 },
  "fuji-xt4": { id: "fuji-xt4", model: "X-T4", cropFactor: 1.5 },
  "fuji-xt5": { id: "fuji-xt5", model: "X-T5", cropFactor: 1.5 },
  "fuji-xt30": { id: "fuji-xt30", model: "X-T30", cropFactor: 1.5 },
  "fuji-xt30-ii": { id: "fuji-xt30-ii", model: "X-T30 II", cropFactor: 1.5 },
  "fuji-xt50": { id: "fuji-xt50", model: "X-T50", cropFactor: 1.5 },
  "fuji-xh1": { id: "fuji-xh1", model: "X-H1", cropFactor: 1.5 },
  "fuji-xh2": { id: "fuji-xh2", model: "X-H2", cropFactor: 1.5 },
  "fuji-xh2s": { id: "fuji-xh2s", model: "X-H2S", cropFactor: 1.5 },
  "fuji-xs10": { id: "fuji-xs10", model: "X-S10", cropFactor: 1.5 },
  "fuji-xs20": { id: "fuji-xs20", model: "X-S20", cropFactor: 1.5 },
  "fuji-xm5": { id: "fuji-xm5", model: "X-M5", cropFactor: 1.5 },
  "fuji-gfx50s": { id: "fuji-gfx50s", model: "GFX 50S", cropFactor: 0.79 },
  "fuji-gfx100s": { id: "fuji-gfx100s", model: "GFX 100S", cropFactor: 0.79 },
  "fuji-gfx100-ii": { id: "fuji-gfx100-ii", model: "GFX 100 II", cropFactor: 0.79 },
  "sony-rx1": { id: "sony-rx1", model: "RX1", cropFactor: 1, fixedLens: { minFocal: 35, maxFocal: 35, maxAperture: 2 } },
  "sony-rx1r-ii": { id: "sony-rx1r-ii", model: "RX1R II", cropFactor: 1, fixedLens: { minFocal: 35, maxFocal: 35, maxAperture: 2 } },
  "sony-rx100-v": { id: "sony-rx100-v", model: "RX100 V", cropFactor: 2.7, fixedLens: { minFocal: 8.8, maxFocal: 25.7, maxAperture: 1.8 } },
  "sony-rx100-vii": { id: "sony-rx100-vii", model: "RX100 VII", cropFactor: 2.7, fixedLens: { minFocal: 9, maxFocal: 72, maxAperture: 2.8 } },
  "sony-a7": { id: "sony-a7", model: "a7", cropFactor: 1 },
  "sony-a7-ii": { id: "sony-a7-ii", model: "a7 II", cropFactor: 1 },
  "sony-a7-iii": { id: "sony-a7-iii", model: "a7 III", cropFactor: 1 },
  "sony-a7-iv": { id: "sony-a7-iv", model: "a7 IV", cropFactor: 1 },
  "sony-a7r-iii": { id: "sony-a7r-iii", model: "a7R III", cropFactor: 1 },
  "sony-a7r-iv": { id: "sony-a7r-iv", model: "a7R IV", cropFactor: 1 },
  "sony-a7r-v": { id: "sony-a7r-v", model: "a7R V", cropFactor: 1 },
  "sony-a7s-iii": { id: "sony-a7s-iii", model: "a7S III", cropFactor: 1 },
  "sony-a7c": { id: "sony-a7c", model: "a7C", cropFactor: 1 },
  "sony-a7c-ii": { id: "sony-a7c-ii", model: "a7C II", cropFactor: 1 },
  "sony-a7cr": { id: "sony-a7cr", model: "a7CR", cropFactor: 1 },
  "sony-a9": { id: "sony-a9", model: "a9", cropFactor: 1 },
  "sony-a9-iii": { id: "sony-a9-iii", model: "a9 III", cropFactor: 1 },
  "sony-a1": { id: "sony-a1", model: "a1", cropFactor: 1 },
  "sony-a6000": { id: "sony-a6000", model: "a6000", cropFactor: 1.5 },
  "sony-a6300": { id: "sony-a6300", model: "a6300", cropFactor: 1.5 },
  "sony-a6400": { id: "sony-a6400", model: "a6400", cropFactor: 1.5 },
  "sony-a6600": { id: "sony-a6600", model: "a6600", cropFactor: 1.5 },
  "sony-a6700": { id: "sony-a6700", model: "a6700", cropFactor: 1.5 },
  "sony-zv-e10": { id: "sony-zv-e10", model: "ZV-E10", cropFactor: 1.5 },
  "sony-zv-e1": { id: "sony-zv-e1", model: "ZV-E1", cropFactor: 1 },
  "leica-q": { id: "leica-q", model: "Q (Typ 116)", cropFactor: 1, fixedLens: { minFocal: 28, maxFocal: 28, maxAperture: 1.7 } },
  "leica-q2": { id: "leica-q2", model: "Q2", cropFactor: 1, fixedLens: { minFocal: 28, maxFocal: 28, maxAperture: 1.7 } },
  "leica-q3": { id: "leica-q3", model: "Q3", cropFactor: 1, fixedLens: { minFocal: 28, maxFocal: 28, maxAperture: 1.7 } },
  "leica-q3-43": { id: "leica-q3-43", model: "Q3 43", cropFactor: 1, fixedLens: { minFocal: 43, maxFocal: 43, maxAperture: 2 } },
  "leica-dlux-7": { id: "leica-dlux-7", model: "D-Lux 7", cropFactor: 2, fixedLens: { minFocal: 10.9, maxFocal: 34, maxAperture: 1.7 } },
  "leica-m-240": { id: "leica-m-240", model: "M (Typ 240)", cropFactor: 1 },
  "leica-m10": { id: "leica-m10", model: "M10", cropFactor: 1 },
  "leica-m10-r": { id: "leica-m10-r", model: "M10-R", cropFactor: 1 },
  "leica-m11": { id: "leica-m11", model: "M11", cropFactor: 1 },
  "leica-sl": { id: "leica-sl", model: "SL (Typ 601)", cropFactor: 1 },
  "leica-sl2": { id: "leica-sl2", model: "SL2", cropFactor: 1 },
  "leica-sl2-s": { id: "leica-sl2-s", model: "SL2-S", cropFactor: 1 },
  "leica-sl3": { id: "leica-sl3", model: "SL3", cropFactor: 1 },
  "leica-cl": { id: "leica-cl", model: "CL", cropFactor: 1.5 },
  "leica-tl2": { id: "leica-tl2", model: "TL2", cropFactor: 1.5 },
};
